### DISCUSSION TITLE
How to connect esp32 to BMS?

### DISCUSSION THREAD

**Discussion by man55** [syssi/esphome-tianpower-bms#22] [Q&A]
How to connect esp32 to BMS? I couldn't find instructions anywhere, sorry.

Basen is Basengreen?
I have Basengreen BR-OW-LV 14.33KWH.

**Comment by syssi** [comment]
Does your battery bank support bluetooth? Could you provide a link to the Android app which supports your battery?

**Comment by man55** [comment]
Yes of course it’s support Bluetooth (and wifi too). 
https://play.google.com/store/apps/details?id=com.green.basen.jizhi&hl=uk

**Reply by syssi** [reply]
Alright. Last question: Is this your first ESPHome node and do you use Home Assistant?

**Comment by man55** [comment]
I use home assistant for 2 years now. I have some esphome node which are connected directly to managed devices according to the instructions provided by the firmware developers.

**Reply by syssi** [reply]
That's perfect. So I don't need to explain the basic and you should already know how to flash a YAML configuration to a new ESPHome node.

1. Download this YAML configuration: https://raw.githubusercontent.com/syssi/esphome-basen-bms/main/esp32-ble-example.yaml
2. Replace the MAC address example with the MAC address of your BMS (`mac_address: A4:C1:38:27:48:9A`).
3. Flash the updated YAML configuration to your ESP32
4. Add the ESPHome to your Home Assistant instance

**Reply by man55** [reply]
Thank you!
Tomorrow I’ll try.

**Reply by man55** [reply]
Where I can find MAC address of BMS?

**Reply by syssi** [reply]
You could add a BLE scanner app on your android. May be the MAC address is also shown at the Android app of the BMS.

**Reply by syssi** [reply]
If you have trouble to find the MAC address you could flash this YAML: https://github.com/syssi/esphome-tianpower-bms/blob/main/esp32-ble-scanner.yaml

It will print all advertised devices to the log if the BLE name starts with `TP`.

**Comment by syssi** [comment]
I've moved the discussion to the `esphome-tianpower-bms` project because it looks like your battery is equipped with a Tianpower BMS and you should use this YAML configuration instead: https://github.com/syssi/esphome-tianpower-bms/blob/main/esp32-ble-example.yaml

I wasn't completely awake yesterday. :-)

**Reply by man55** [reply]
Thanks, yes it looks like it.

I found the MAC address in the android app. I usually use an iPhone and it's not there.

I'm setting up YAML now and have a few questions:

1. Should I add MQTT lines like this because in YAML it is written differently and I am confused.:
```
mqtt_host: MY_MQTT_HOST
mqtt_username: MY_MQTT_USERNAME
mqtt_password: MY_MQTT_PASSWORD
```
2. Where exactly in what lines do I need to enter the ID/name of my BMS (BSTBD-24C-0233)?

3. In what lines can I change "tianpower" to "Basengreen" so that in HA the name of the device and sensors corresponds to the real name (basengreen)?

```
substitutions:
  name: tianpower-bms-ble
  device_description: "Monitor a Basengreen Battery Management System via BLE"
  external_components_source: github://syssi/esphome-tianpower-bms@main
  mac_address: 44:1A:xx:xx:xx:xx

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-tianpower-bms"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:
  reboot_timeout: 0s

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: BSTBD-24C-0233

tianpower_bms_ble:
  - ble_client_id: BSTBD-24C-0233
    id: bms0
    update_interval: 10s

binary_sensor:
  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms0
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    limiting_current:
      name: "${name} limiting current"

sensor:
  - platform: tianpower_bms_ble
```

**Reply by man55** [reply]
And my esp is:
```
esp32:
  board: esp32dev
  framework:
    type: arduino
```

Is this OK ?
![IMG_0276](https://github.com/user-attachments/assets/3d55fa22-965c-47cd-8fa5-ca38b8cc568a)

**Reply by syssi** [reply]
1. People which doesn't use Home Assistant prefer `mqtt` over `api`. You should stick to the native `api`. You should see `mqtt` as replacement.
2. The name of the BMS isn't important. If you want to change to hostname of the ESPHome node feel free.
3. Update the `name` substitution from `tianpower-bms-ble` to `basengreen` or something else. This variable is used as hostname and as prefix of all entities.

**Reply by syssi** [reply]
IMO your board is a Wemos D1 Mini32 clone and you could use

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
```

At the end it doesn't matter because we are not interested in the proper assignment of the labels (`D1`, `D2`, ..., `A0`) on the PCB.

**Reply by syssi** [reply]
I recommend the `framework.type` ESP-IDF over Arduino.

**Comment by man55** [comment]
How to write the device name correctly? 
During validation, it swears at the dash
![Снимок экрана 2024-07-23 104328](https://github.com/user-attachments/assets/f72a9ac1-949e-40ac-b4ed-5c91ceae878e)


```
ble_client:
  - mac_address: ${mac_address}
    id: TP_BSTBD-24C-0232

tianpower_bms_ble:
  - ble_client_id: TP_BSTBD-24C-0232
    id: bms0
    update_interval: 10s
```

**Reply by syssi** [reply]
Could you provide your complete YAML? I'm confused about the `id:`.

**Reply by syssi** [reply]
```
ble_client:
  - mac_address: ${mac_address}
    id: TP_BSTBD_24C_0232

tianpower_bms_ble:
  - ble_client_id: TP_BSTBD_24C_0232
    id: bms0
    update_interval: 10s
```

**Reply by syssi** [reply]
This is just an internal naming. You could also use any shorthands:

```
ble_client:
  - mac_address: ${mac_address}
    id: tp0

tianpower_bms_ble:
  - ble_client_id: tp0
    id: bms0
    update_interval: 10s
```

**Comment by man55** [comment]
OMG its working ))
Thanks again! Sent you a coffee.
![Снимок экрана 2024-07-23 113134](https://github.com/user-attachments/assets/42c49324-869e-4b83-89f7-de3f89147d8c)
![Снимок экрана 2024-07-23 113019](https://github.com/user-attachments/assets/459ad3ea-80f6-499e-abc4-86aa3d1805df)

p.s. What do these lines in the logs mean?
```
[11:27:51][W][component:237]: Component esp32_ble took a long time for an operation (111 ms).
[11:27:51][W][component:238]: Components should block for at most 30 ms.
```

**Reply by syssi** [reply]
The parser just needs some time to decode the data. You can ignore this warning.

**Comment by syssi** [comment]
Could you provide some details about your BMS? I would like to extend the list of supported devices / battery banks:

https://github.com/syssi/esphome-tianpower-bms?tab=readme-ov-file#supported-devices

**Reply by syssi** [reply]
The most important question is: What's the advertised name of your BMS? A complete ESPHome log would help here or a screenshot of the first view (discovered devices) of the Android app.

**Reply by syssi** [reply]
Are these details correct? https://github.com/syssi/esphome-tianpower-bms/pull/26/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R24-R26

**Reply by man55** [reply]
Android app does not show anything except the MAC address and the name, which can be changed via the original software for windows.

I couldn’t find how to view the full ESPHome log, the visible piece contains nothing.

But via the original software for windows I can see this: BMS: BN-HES16S48V200LT55A-V1.1.2
But Google knows nothing about this, most likely this is a custom BMS ordered from the OEM manufacturer and named something at will.

The battery link : www.basengreen.com/ru/product/eu-stock-51-2v-280ah-14-3kwh-wall-mounted-lifepo4-battery-pack-lifepo4-for-solar-energy-storage/

**Reply by man55** [reply]
> Are these details correct? https://github.com/syssi/esphome-tianpower-bms/pull/26/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R24-R26

I think yes.

**Comment by man55** [comment]
what is the minimum _update_interval_ I can set?
```
tianpower_bms_ble:
  - ble_client_id: TP_BSTBD_24C_0232
    id: bms0
    update_interval: 10s
```
