### ISSUE TITLE
2 Basen battery

### ISSUE THREAD

**Issue by italodl** [syssi/esphome-tianpower-bms#21]
hi, I have 2 basen batteries and two esp32. I can't configure the second battery. the sensors have the same name and do not work. Is it possible to make both work?

**Comment by syssi** [comment]
Could you increase the log level

```
logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble: DEBUG
    esp32_ble_tracker: VERY_VERBOSE
    tianpower_bms_ble: VERY_VERBOSE
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```

and provide some logs of both batteries?

**Comment by syssi** [comment]
Could you provide some more details? For example are the ESP32 models different? It looks like ESP32S and ESP32-C3 models doesn't to a good job on Bluetooth at the moment.

**Comment by syssi** [comment]
If the naming of the sensors the only issue and the data arrives properly already you have to make sure the ESPHome nodes has different names:

```
# first node

substitutions:
  name: tianpower-bms-ble

# ...

sensor:
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
```

```
# second node

substitutions:
  name: tianpower-bms-ble2

# ...

sensor:
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
```

The `name` is part of the entities.
