### ISSUE TITLE
MQTT topic

### ISSUE THREAD

**Issue by valdiks** [syssi/esphome-tianpower-bms#32]
Hi, how can I make that a part from mqtt publish topic is not used:
tianpower-bms-ble/sensor/**tianpower-bms-ble_**total_voltage/state
to make like this:
tianpower-bms-ble/sensor/total_voltage/state
![tianbms](https://github.com/user-attachments/assets/56f77847-1c3e-4805-b623-59e7307c5b68)

It makes some unnecessary overhead to use in node-red and Telegraf input plugin to write to the influxdb

**Comment by syssi** [comment]
Just remove the `${name} ` substitution from all entities:

```
# old

sensor:
  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms0
    voltage_protection_bitmask:
      name: "${name} voltage protection bitmask"
    current_protection_bitmask:
      name: "${name} current protection bitmask"
```

```
# new

sensor:
  - platform: tianpower_bms_ble
    tianpower_bms_ble_id: bms0
    voltage_protection_bitmask:
      name: "voltage protection bitmask"
    current_protection_bitmask:
      name: "current protection bitmask"
